### ISSUE TITLE
'Unable to cast object of type 'MongoDB.Bson.BsonDocument' to type 'MongoDB.Bson.BsonArray'

### ISSUE THREAD

**Issue by arkoc** [object/MongOData#28]
When JSON document has following structure:

``` json
{
  "Id" : "436A412D-1FFA-492B-96EC-A534F600E0D8",
  "Data" : {
    "Form" : [{
        "style" : {
          "add" : "btn-success"
        }
      }, {
           "style" : "btn-success"
      }]
  }
}
```

data-service fail with exception:

> Unable to cast object of type 'MongoDB.Bson.BsonDocument' to type 'MongoDB.Bson.BsonArray

I think it is because that in first element of array `style` is `object` but in second one just `string`.

I guess that this document isn't something that should be exported to oData feed, but now we have no mechanism to restrict `MongOData` using some collections ( that may have data of this kind ).

I think we need solution to restrict `MongOData` collection. If you agree, I can contribute it.

**Comment by object** [comment]
Yes, I think the problem lies in mismatch between schemaless nature of MongoDB documents and OData protocol demanding mapping document elements to some schema. I haven't thought about possibility to restrict MongOData collections, but if you have some ideas, please go ahead.

**Comment by arkoc** [comment]
Ok, I think it is necessary to add configuration settings under the `MongOData` section like this:

``` xml
<MongOData>
    <metadataBuildStrategy>
        <prefetchRows>10</prefetchRows>
        <fetchPosition>end</fetchPosition>
        <updateDynamically>false</updateDynamically>
        <persistSchema>false</persistSchema>
    </metadataBuildStrategy>
    <excludeCollections>
        <add db="database1" collection="schema1" />
        <add db="database2" collection="schema2" />
    </excludeCollections>
</MongOData>
```

Then use this information in `MongoMetadata.GetCollectionNames` method.

What you think about this ?

**Comment by arkoc** [comment]
I ended up with creating separate user in MongoDB for `MongOData` and restricting access to `bad` collections.
